### ISSUE TITLE
在D盘一级目录下运行anywhere会出错，为什么？

### ISSUE THREAD

**Issue by airsaly** [JacksonTian/anywhere#16]
安装是
npm install anywhere -g

但在D盘一级目录 运行会出现以下错误：
Running at http://192.168.11.217:8000/
Error: EPERM, stat 'D:\Config.Msi'
    at Error (native)

二级目录下又可以正常运行了，求答疑！

**Comment by JacksonTian** [comment]
EPERM。权限问题。
