### ISSUE TITLE
这个可以实现http上传下载文件吗?

### ISSUE THREAD

**Issue by yzk0281** [JacksonTian/anywhere#17]
请问 这个可以实现http上传下载文件吗?

**Comment by JacksonTian** [comment]
静态文件服务器

发自我的 iPhone

**Comment by shy2850** [comment]
@yzk0281  如果你想要一个更多功能的node服务器，可以考虑一下 [f2e-server](http://f2e-server.com)。 anywhere目前看来更专注于作为纯粹的静态文件服务器， 而f2e-server的定位是开发调试用的服务器。

**Comment by liangzai-cool** [comment]
看起来的确不错的样纸 @shy2850 :smirk:

**Comment by lqbilbo** [comment]
怎么会有这么好用的东东 @shy2850
