### ISSUE TITLE
anywhere的用途在哪？

### ISSUE THREAD

**Issue by naffan2014** [JacksonTian/anywhere#21]
想不到随便把一个目录当做静态文件服务器的用途在哪里？可以给举个能直接体现功能的例子么？

**Comment by hstarorg** [comment]
下载一个demo到本地，需要看的时候。很多时候直接双击打开不友好。

**Comment by naffan2014** [comment]
比如那个方面不友好呢？能给个细节的例子吗？

**Comment by hstarorg** [comment]
@naffan2014 如果静态页面，会有访问本地json之类的，或者其他需要服务器支持的场景，直接双击打开就看不到。

**Comment by JacksonTian** [comment]
前端开发，从设计稿开始编写HTML+CSS的时候，套mock数据等。
