### ISSUE TITLE
support gzip?

### ISSUE THREAD

**Issue by uinz** [JacksonTian/anywhere#26]

**Comment by JacksonTian** [comment]
这个是开发时用的工具。没有用gzip做优化的必要。

**Comment by uinz** [comment]
但是我做完一个项目想看看gizp后压缩了多少, 顺便用chrome 感受下打开速度.

**Comment by hstarorg** [comment]
这个还要看你配置多大的压缩比。这种测试应该在预发布环境中进行测试，保证和发布环境基本一致。

**Comment by uinz** [comment]
感谢, 思考了下 确实没有太多必要.
