### ISSUE TITLE
可否增加配置项，用来过滤文件后缀

### ISSUE THREAD

**Issue by chrunlee** [JacksonTian/anywhere#29]
增加一些过滤配置项，用来包含或过滤文件后缀。
在某些情况下，只想将某些文件比如.txt .js .css 等类型文件展示出来，或者不想展示出 .exe .bat 等文件。

**Comment by JacksonTian** [comment]
用在什么场景啊

**Comment by chrunlee** [comment]
我这边目前有的场景是：在开发的时候想看到服务器上的日志，但是日志在多个tomcat中，所以就想把外层文件夹直接当作目录全部展示出来，不过最终目的只是想看日志，不想看到其他的一些配置项。

**Comment by JacksonTian** [comment]
这种操作是很危险的吧。限制客户端了吗。

**Comment by chrunlee** [comment]
本来是想加basicAuth的，不过感觉应该没啥大问题吧，只是一些日志或者配置，而且只能看和下载。

**Comment by JacksonTian** [comment]
配置本身就很敏感。注意安全。

**Comment by chrunlee** [comment]
那能加入basicAuth么，如果不介意的话，我可以提个pr么 
想加入三个配置项：include exclude auth ,serve-index 版本提升到1.9.1.

**Comment by JacksonTian** [comment]
加 basic auth 不符合设计初衷，建议你自己写一个模块来满足需求。
