### ISSUE TITLE
可否都重定向到首页

### ISSUE THREAD

**Issue by arsen2010** [JacksonTian/anywhere#30]
SPA模式下，路由都是前端识别的，页面都只需重定向到首页，比如访问/user/center, 实际只想它跳到/index.html，其他的模块/user/center都由js加载，可否做到，怎么做，谢谢回答！

**Comment by hstarorg** [comment]
请使用 `-f` 参数。

**Comment by arsen2010** [comment]
谢谢，有效，文档那边写-f :enable html5 history，我以为跟这个定向没关系

**Comment by hstarorg** [comment]
当时我也有这需求，所以就加了。

**Comment by arsen2010** [comment]
可否支持spa方式中类似带文件后缀的 url 地址请求，例如访问 http://localhost:8001/doc/ui.isArray，
当页面初次访问或刷新的时候会报错 Cannot GET /doc/ui.isArray
知道是把它当作静态文件处理了，那能否有静态文件的白名单支持，不在白名单中的都跳到首页
版本大于1.5.0 命令是 anywhere -h localhost -d ../dist -p 8001 -f /index.html

**Comment by hstarorg** [comment]
@arsen2010  你这个确实与标准不符合，建议将你的URL标准化。

**Comment by arsen2010** [comment]
@hstarorg 你好，这边的场景是前后端分离，前端SPA，web server除了静态文件服务，还有一些路由跳转的要求（如我这个重定向的场景，如数据mock的场景（目前无需求））；
/doc/ui.isArray 是合规的url地址，从spa和不用seo的角度说，语义化的url出于记忆方面的考虑，不一定要标准化；
anywhere用于开发环境，因为前端工具的一体化启动而更有优势，生成环境会用nginx；
如果你有时间的话，请考虑下是否有必要补上这一特性，使anywhere适用更多场景，谢谢了。
我在自己的另一个前端项目中准备推荐使用anywhere，https://github.com/pageborn/jqueryapp

**Comment by hstarorg** [comment]
@arsen2010 你只要把url化成ui_isArray即可。 ui.isArray会破坏对静态资源的解析。

**Comment by JacksonTian** [comment]
先 close 了，有问题再 re-open 。
