### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [JacksonTian/anywhere#33]
Hi,

I'm a member of the Node.js Security WG and we received a report regarding a security issue with this module.

We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by JacksonTian** [comment]
Hi @lirantal I have updated the dependencies and published new version.

Thanks for you pay attention.

**Comment by lirantal** [comment]
@JacksonTian thanks, appreciate the quick response.

Can you please jump in on the Hacker1 platform with the e-mail invite you received in your inbox and continue the conversation with the bug hunter who reported it?
