### ISSUE TITLE
关闭zsh的窗口之后服务并没有关闭

### ISSUE THREAD

**Issue by RyanLiu0235** [JacksonTian/anywhere#34]
我没有`cmd+c`退出Node.js，而是直接关闭了zsh窗口，然后我启动的服务并没有停止，需要我找到对应的pid然后手动kill。请问能解决一下么？

**Comment by stop2stare** [comment]
@hstarorg emmm...我的意思是我首先开启了一个anywhere服务，80端口。然后我直接关闭了zsh，之前并没有手动使用`cmd+c`退出anywhere服务。这时候80端口的服务依然还在后台运行。
所以请问能否支持一下直接关闭窗口也能退出anywhere服务。不然退了手动去kill进程很难受。

**Comment by hstarorg** [comment]
是哇，我是指没有发现有代码会这样。用系统控制台会出现这个问题么？

**Comment by stop2stare** [comment]
对的，我本地是macOS Sierra zsh+iterm2，然后开了80端口的服务。就会复现上面的场景。

**Comment by JacksonTian** [comment]
按道理 session 退出后会关闭相关进程的。

**Comment by stop2stare** [comment]
@JacksonTian 确实应该关闭进程，可能我开的是80端口的原因？您本地能复现么？

**Comment by JacksonTian** [comment]
我没有用 zsh 也没有用 iterm2 。先关了，有问题再 reopen。
