### ISSUE TITLE
it can't works any more

### ISSUE THREAD

**Issue by CracKerMe** [JacksonTian/anywhere#36]
node version: 8.9.2
npm version: 5.5.1
OS : windows 10

it works before in former version & how to resolve that

waiting for your reply

**Comment by hstarorg** [comment]
Is there any error message?

**Comment by CracKerMe** [comment]
no, it just run as before,but when open the browser automatically,it's waiting for a very long time and connect time out

**Comment by CracKerMe** [comment]
oh my god , it works just now . i promise that i did nothing before.   thanks a lot
