### ISSUE TITLE
需求：展示选项，增加图片预览

### ISSUE THREAD

**Issue by biaomingzhong** [JacksonTian/anywhere#37]
可以增加图片预览的功能吗？

**Comment by hstarorg** [comment]
会不会有点脱离该工具的核心目的？

**Comment by biaomingzhong** [comment]
该工具就是为了静态服务器，展示文件和目录

**Comment by JacksonTian** [comment]
图片预览 用系统工具不就可以了吗。

**Comment by biaomingzhong** [comment]
本来是想在一台公共的电脑上建一个静态服务器可以浏览一些文件，可以支持预览一些资源。
类似如下：底下很多图片的时候，可以预览，而不是一个个图片点击打开才能看
![image](https://user-images.githubusercontent.com/5178619/42720489-1c79c57e-875a-11e8-813f-bd9ec67bbf21.png)

**Comment by JacksonTian** [comment]
预览 可能是个大坑了。
